# Generated by cucumber-sinatra. (2015-08-04 11:48:51 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/battleships_web.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Battleshipsweb

class BattleshipswebWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BattleshipswebWorld.new
end
